# Generated by Django 5.1.6 on 2025-02-25 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_alter_vinos_etiqueta_alter_vinos_variedad'),
    ]

    operations = [
        migrations.AddField(
            model_name='vinos',
            name='fecha_creacion',
            field=models.DateField(null=True),
        ),
    ]
