# Generated by Django 5.1.6 on 2025-02-27 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0004_alter_vinos_fecha_creacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='vinos',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imagen'),
        ),
    ]
