# Generated by Django 5.1.6 on 2025-02-27 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0005_vinos_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vinos',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes'),
        ),
    ]
