# Generated by Django 5.1.6 on 2025-02-26 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='infoextra',
            name='hobbies',
            field=models.TextField(blank=True, null=True),
        ),
    ]
