# Generated by Django 5.1.6 on 2025-02-27 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_infoextra_hobbies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infoextra',
            name='hobbies',
        ),
    ]
