# Generated by Django 5.1.6 on 2025-02-27 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_infoextra_hobbies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infoextra',
            name='hobbies',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
